/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace KhataFlowPayments {
  export type PaymentScheduleStruct = {
    debtTokenId: BigNumberish;
    totalAmountPaise: BigNumberish;
    installmentPaise: BigNumberish;
    frequencySeconds: BigNumberish;
    nextDueUnix: BigNumberish;
    paidInstallments: BigNumberish;
    totalInstallments: BigNumberish;
    active: boolean;
    businessWallet: AddressLike;
  };

  export type PaymentScheduleStructOutput = [
    debtTokenId: bigint,
    totalAmountPaise: bigint,
    installmentPaise: bigint,
    frequencySeconds: bigint,
    nextDueUnix: bigint,
    paidInstallments: bigint,
    totalInstallments: bigint,
    active: boolean,
    businessWallet: string
  ] & {
    debtTokenId: bigint;
    totalAmountPaise: bigint;
    installmentPaise: bigint;
    frequencySeconds: bigint;
    nextDueUnix: bigint;
    paidInstallments: bigint;
    totalInstallments: bigint;
    active: boolean;
    businessWallet: string;
  };
}

export interface KhataFlowPaymentsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelSchedule"
      | "createSchedule"
      | "getSchedule"
      | "isPaymentOverdue"
      | "recordInstallment"
      | "schedules"
      | "tokenToSchedule"
      | "totalSchedules"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InstallmentRecorded"
      | "ScheduleCancelled"
      | "ScheduleCompleted"
      | "ScheduleCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelSchedule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSchedule",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getSchedule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPaymentOverdue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordInstallment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "schedules",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenToSchedule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSchedules",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPaymentOverdue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordInstallment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "schedules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenToSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSchedules",
    data: BytesLike
  ): Result;
}

export namespace InstallmentRecordedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    installmentNumber: BigNumberish,
    nextDueUnix: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    installmentNumber: bigint,
    nextDueUnix: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    installmentNumber: bigint;
    nextDueUnix: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleCancelledEvent {
  export type InputTuple = [scheduleId: BigNumberish];
  export type OutputTuple = [scheduleId: bigint];
  export interface OutputObject {
    scheduleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleCompletedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    debtTokenId: BigNumberish
  ];
  export type OutputTuple = [scheduleId: bigint, debtTokenId: bigint];
  export interface OutputObject {
    scheduleId: bigint;
    debtTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleCreatedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    debtTokenId: BigNumberish,
    totalInstallments: BigNumberish,
    frequencySeconds: BigNumberish,
    firstDueUnix: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    debtTokenId: bigint,
    totalInstallments: bigint,
    frequencySeconds: bigint,
    firstDueUnix: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    debtTokenId: bigint;
    totalInstallments: bigint;
    frequencySeconds: bigint;
    firstDueUnix: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KhataFlowPayments extends BaseContract {
  connect(runner?: ContractRunner | null): KhataFlowPayments;
  waitForDeployment(): Promise<this>;

  interface: KhataFlowPaymentsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelSchedule: TypedContractMethod<
    [scheduleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createSchedule: TypedContractMethod<
    [
      debtTokenId: BigNumberish,
      totalAmountPaise: BigNumberish,
      totalInstallments: BigNumberish,
      frequencySeconds: BigNumberish,
      firstDueUnix: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getSchedule: TypedContractMethod<
    [scheduleId: BigNumberish],
    [KhataFlowPayments.PaymentScheduleStructOutput],
    "view"
  >;

  isPaymentOverdue: TypedContractMethod<
    [scheduleId: BigNumberish],
    [boolean],
    "view"
  >;

  recordInstallment: TypedContractMethod<
    [scheduleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  schedules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        debtTokenId: bigint;
        totalAmountPaise: bigint;
        installmentPaise: bigint;
        frequencySeconds: bigint;
        nextDueUnix: bigint;
        paidInstallments: bigint;
        totalInstallments: bigint;
        active: boolean;
        businessWallet: string;
      }
    ],
    "view"
  >;

  tokenToSchedule: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  totalSchedules: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelSchedule"
  ): TypedContractMethod<[scheduleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSchedule"
  ): TypedContractMethod<
    [
      debtTokenId: BigNumberish,
      totalAmountPaise: BigNumberish,
      totalInstallments: BigNumberish,
      frequencySeconds: BigNumberish,
      firstDueUnix: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSchedule"
  ): TypedContractMethod<
    [scheduleId: BigNumberish],
    [KhataFlowPayments.PaymentScheduleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPaymentOverdue"
  ): TypedContractMethod<[scheduleId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordInstallment"
  ): TypedContractMethod<[scheduleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "schedules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        debtTokenId: bigint;
        totalAmountPaise: bigint;
        installmentPaise: bigint;
        frequencySeconds: bigint;
        nextDueUnix: bigint;
        paidInstallments: bigint;
        totalInstallments: bigint;
        active: boolean;
        businessWallet: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenToSchedule"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSchedules"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "InstallmentRecorded"
  ): TypedContractEvent<
    InstallmentRecordedEvent.InputTuple,
    InstallmentRecordedEvent.OutputTuple,
    InstallmentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleCancelled"
  ): TypedContractEvent<
    ScheduleCancelledEvent.InputTuple,
    ScheduleCancelledEvent.OutputTuple,
    ScheduleCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleCompleted"
  ): TypedContractEvent<
    ScheduleCompletedEvent.InputTuple,
    ScheduleCompletedEvent.OutputTuple,
    ScheduleCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleCreated"
  ): TypedContractEvent<
    ScheduleCreatedEvent.InputTuple,
    ScheduleCreatedEvent.OutputTuple,
    ScheduleCreatedEvent.OutputObject
  >;

  filters: {
    "InstallmentRecorded(uint256,uint256,uint256)": TypedContractEvent<
      InstallmentRecordedEvent.InputTuple,
      InstallmentRecordedEvent.OutputTuple,
      InstallmentRecordedEvent.OutputObject
    >;
    InstallmentRecorded: TypedContractEvent<
      InstallmentRecordedEvent.InputTuple,
      InstallmentRecordedEvent.OutputTuple,
      InstallmentRecordedEvent.OutputObject
    >;

    "ScheduleCancelled(uint256)": TypedContractEvent<
      ScheduleCancelledEvent.InputTuple,
      ScheduleCancelledEvent.OutputTuple,
      ScheduleCancelledEvent.OutputObject
    >;
    ScheduleCancelled: TypedContractEvent<
      ScheduleCancelledEvent.InputTuple,
      ScheduleCancelledEvent.OutputTuple,
      ScheduleCancelledEvent.OutputObject
    >;

    "ScheduleCompleted(uint256,uint256)": TypedContractEvent<
      ScheduleCompletedEvent.InputTuple,
      ScheduleCompletedEvent.OutputTuple,
      ScheduleCompletedEvent.OutputObject
    >;
    ScheduleCompleted: TypedContractEvent<
      ScheduleCompletedEvent.InputTuple,
      ScheduleCompletedEvent.OutputTuple,
      ScheduleCompletedEvent.OutputObject
    >;

    "ScheduleCreated(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;
    ScheduleCreated: TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;
  };
}
